# Generated by Django 6.1.1 on 2026-09-08 10:28

import apps.videos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField()),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=10000)),
                ('language', models.CharField(default='en', max_length=10)),
                ('original_file', models.FileField(max_length=500, upload_to=apps.videos.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.videos.models.thumbnail_upload_path)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('made_for_kids', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channels.channel')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='videos.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveSmallIntegerField()),
                ('file', models.FileField(max_length=500, upload_to=apps.videos.models.rendition_upload_path)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='videos.video')),
            ],
            options={
                'ordering': ['resolution'],
            },
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('watch_seconds', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='direct', max_length=30)),
                ('counted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='videos.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videos_vide_slug_92e2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'visibility'], name='videos_vide_status_1398c6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-published_at'], name='videos_vide_publish_c5c637_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view_count'], name='videos_vide_view_co_02bc14_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='videos_vide_categor_5f133b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videorendition',
            unique_together={('video', 'resolution')},
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['video', 'created_at'], name='videos_vide_video_i_234b72_idx'),
        ),
        migrations.AddIndex(
            model_name='videoview',
            index=models.Index(fields=['session_key'], name='videos_vide_session_5ec04a_idx'),
        ),
    ]
